---
- name: Install and configure LibreNMS server
  hosts: librenms_server
  become: true

  pre_tasks:
    - name: Upadate apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Include vars
      ansible.builtin.include_vars: vars/config.yaml

  handlers:
    - name: Load handlers
      ansible.builtin.import_tasks: tasks/handlers.yaml

  tasks:
    - name: Create librenms user
      ansible.builtin.import_tasks: tasks/configure_user.yaml
    - name: Install packages
      ansible.builtin.import_tasks: tasks/install_packages.yaml
